"""
gen_dft.py -- writes the four separable-DFT stage codeboxes for f_vf_fluid from
one template (plan ADR-4). Axis and direction are baked in as constants so no
Param has to arrive before the first compile.

    fx  forward DFT along x     fy  forward DFT along y
    iy  inverse DFT along y     ix  inverse DFT along x  (+ real part + NaN/Inf guard)

Run:  python3 src/f_vf_fluid/gen_dft.py            (writes codebox_dft_*.gen next to it)
N is a hard constant (256). Its literal appears exactly twice in each file's
code (the N assignment and the loop bound) and nowhere in comments; this script
asserts that, as bench_fft.py's substitution relies on the same rule.
Mirror: tests/test_fft_separable.pass_dft; stage semantics: tests/fluid_mirror.py.
"""
from pathlib import Path

N = 256
HERE = Path(__file__).resolve().parent

HEADER = """\
// {name} -- f_vf_fluid stage {stage}: {title}.
// GENERATED by gen_dft.py from one template -- edit the template, not this file.
// Mirror: tests/test_fft_separable.pass_dft(axis="{axis}", inverse={inv}).
//
// Packing (float32 RGBA): R,G = Re,Im of u; B,A = Re,Im of v.
// Carried findings (bench-verified 2026-09-22/23):
//   - integer bin index is floor(norm * N), NOT `cell` (= norm*(dim-1) on jit.gl.pix)
//   - nearest() at texel centers, twiddle index mod(k*n, N) before the angle
//   - components accessed inline on nearest(), never on a stored vector
//   - a NaN/Inf guard must use abs(x) < 1e30 (NaN == NaN is TRUE on this GPU)
//   - no unary minus in front of a product/parenthesis: write `0 - ...` (GenExpr mis-parses it)
"""

BODY_HEAD = """\

N = {n};
k = floor(norm.{axis} * N);

acc0 = 0;
acc1 = 0;
acc2 = 0;
acc3 = 0;

for (n = 0; n < {n}; n += 1) {{
	uv = vec({uvx}, {uvy});
	ang = {sgn}twopi * mod(k * n, N) / N;
	c = cos(ang);
	s = sin(ang);
	acc0 += nearest(in1, uv).x * c - nearest(in1, uv).y * s;
	acc1 += nearest(in1, uv).x * s + nearest(in1, uv).y * c;
	acc2 += nearest(in1, uv).z * c - nearest(in1, uv).w * s;
	acc3 += nearest(in1, uv).z * s + nearest(in1, uv).w * c;
}}
"""

TAIL_PLAIN = """\

out1 = vec(acc0, acc1, acc2, acc3){scale};
"""

TAIL_REAL = """\

// inverse along x is the last transform: keep only the real parts (drops the
// numerical imaginary residue every frame) and zap non-finite values, so a NaN
// can never persist in the feedback loop.
ru = acc0 / N;
rv = acc2 / N;
ru = switch(abs(ru) < 1e30, ru, 0);
rv = switch(abs(rv) < 1e30, rv, 0);
out1 = vec(ru, 0, rv, 0);
"""

STAGES = {
    "fx": dict(stage=2, title="forward DFT along x", axis="x", inv=0),
    "fy": dict(stage=3, title="forward DFT along y", axis="y", inv=0),
    "iy": dict(stage=5, title="inverse DFT along y", axis="y", inv=1),
    "ix": dict(stage=6, title="inverse DFT along x, real part + NaN/Inf guard", axis="x", inv=1),
}


def render(key):
    s = STAGES[key]
    axis, inv = s["axis"], s["inv"]
    name = f"codebox_dft_{key}.gen"
    uvx, uvy = (("(n + 0.5) / N", "norm.y") if axis == "x" else ("norm.x", "(n + 0.5) / N"))
    sgn = "" if inv else "0 - "                   # forward exp(-i...), inverse exp(+i...); never a bare unary minus
    text = HEADER.format(name=name, stage=s["stage"], title=s["title"], axis=axis, inv=inv)
    text += BODY_HEAD.format(n=N, axis=axis, uvx=uvx, uvy=uvy, sgn=sgn)
    if key == "ix":
        text += TAIL_REAL
    else:
        text += TAIL_PLAIN.format(scale=" / N" if inv else "")
    code = "\n".join(l for l in text.split("\n") if not l.lstrip().startswith("//"))
    assert code.count(str(N)) == 2, f"{name}: N literal must appear exactly twice, got {code.count(str(N))}"
    return name, text


def main():
    for key in STAGES:
        name, text = render(key)
        (HERE / name).write_text(text)
        print("wrote", name)


if __name__ == "__main__":
    main()
