"""
spike_scatter.py -- scatter feasibility spike, stages S0-S2 (ideas/optics_map.md, ideas/f_lumia.md).

A record, not a regression gate (it matches no runner and is not registered in benchdeps): it drives
the module bench with tests/bench/spike_scatter.maxpat (generated by make_spike_scatter.py) and
prints what the GPU did against a NumPy emulation of the shader and against the photon-counting
ground truth from scratch/caustic_fidelity.py.

  S0  identity (d = 0, gradient source): does a point grid in a float32 node reproduce its source?
      Also reveals the net vertical orientation of node capture vs the pix chain.
  S0b a uniform field shifts the gradient: identifies BOTH flips (texture upload, capture readback).
  S1  float accumulation: 4096 points land on one pixel. Does the float32 capture hold 4096, or clamp?
  S2  a real glass field vs the NumPy scatter of the same lattice, and vs the photon-counting truth,
      at 0.6, 1.0 and 3.5 x d*.

Needs Max with the module bench open (this script reopens it if not).  Run:
  uv run --no-project --with numpy --with matplotlib python3 tests/spike_scatter.py
"""
import json
import os
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE.parent / "scratch"))

import benchclient as bc          # noqa: E402
import gpu_sim as g               # noqa: E402
import jxf                        # noqa: E402
from modulebench import make_wrapper   # noqa: E402
import caustic_fidelity as cf     # noqa: E402  (field_texture, truth, module_caustic, ...)

F32 = np.float32
R = 256                      # node capture size (make_spike_scatter.py)
TEX = 512                    # input texture size
WARMUP, SETTLE = 30, 24


# ------------------------------------------------------------------ plumbing
def ensure_bench():
    if not bc.ping(2.0, ports=bc.MODULE_PORTS):
        print("module bench not open: reopening (Max comes to the front)")
        bc.reopen(wait=40.0, ports=bc.MODULE_PORTS, patch="bench_module.maxpat")


def run(src, field, params, timeout_ms=90000, settle=SETTLE, warmup=WARMUP,
        module="spike_scatter.maxpat", n_out=1, multi=False):
    """One job. Returns (result, {tag: out1 RGBA}), or {tag: {k: RGBA}} with multi=True. tag 'base' =
    defaults, before any param is sent; tag 'bypassed' = after all params (the module bench's
    timeline names it that way)."""
    job, job_dir = bc.new_job("module", warmup=warmup, settle=settle, timeout_ms=timeout_ms)
    job["wrapper"] = f"mjob_{job['id']}.maxpat"
    job["inputs"] = []
    for i, arr in enumerate((src, field)):
        fn = f"in{i + 1}.jxf"
        jxf.write_rgba(job_dir / fn, np.asarray(arr, F32))
        job["inputs"].append(fn)
    job["params"] = params
    job["readback"], job["controls"] = {}, []
    wrapper = bc.BENCH_DIR / job["wrapper"]
    wrapper.write_text(json.dumps(make_wrapper(module, 2, n_out), indent=2))
    result = bc.run_job(job, job_dir, ports=bc.MODULE_PORTS)
    for old in bc.BENCH_DIR.glob("mjob_*.maxpat"):
        if old != wrapper:
            old.unlink()
    out = {}
    for tag, ks in (result.get("outputs") or {}).items():
        if multi:
            out[tag] = {k: jxf.read_rgba(job_dir / f"{tag}_out{k}.jxf") for k in ks}
        elif 1 in ks:
            out[tag] = jxf.read_rgba(job_dir / f"{tag}_out1.jxf")
    return result, out


def report(result, label):
    errs = result.get("errors") or []
    print(f"  [{label}] status={result.get('status')} frames={result.get('frames_rendered')} "
          f"elapsed={result.get('elapsed_ms')} ms errors={len(errs)}")
    for e in errs[:6]:
        print(f"      max error: {e[:200]}")


# ------------------------------------------------------- NumPy shader emulation
def flip(a, on):
    return a[::-1] if on else a


def ref_scatter(src, field, d, n, w, up_flip=False, out_flip=False, r=R, fy=1.0):
    """What the shader should do. Lattice u_i = i/(n-1) (a plane gridshape spans [-1, 1] inclusive),
    textures sampled bilinear/clamp, each point splatted with a bilinear (tent) footprint, additive.
    (A plain size-1 GL point is round and deposits only if its centre is within 0.5 px of a pixel
    centre: it aliased against the lattice and lost ~21% of the energy, spike S1.)
    up_flip: texture memory = flipud(matrix); out_flip: matrix = flipud(framebuffer).
    fy multiplies the field's Y (the shader's `fy` uniform)."""
    t = (np.arange(n, dtype=np.float64) / (n - 1)).astype(F32)
    U, V = np.meshgrid(t, t)
    f = (g.sample(flip(field, up_flip), U, V)[..., :2] - F32(0.5)) * F32(2.0)
    X = U + F32(d) * f[..., 0]
    Y = V + F32(d) * f[..., 1] * F32(fy)
    # tent (bilinear) splat, as the fragment shader does: pixel k gets 1 - |k + 0.5 - x*r| (if > 0)
    # a point whose CENTRE is outside the viewport is clipped whole (GL clips a point by its centre)
    centre_in = (X >= 0) & (X <= 1) & (Y >= 0) & (Y <= 1)
    fx, fyy = X * F32(r) - F32(0.5), Y * F32(r) - F32(0.5)
    x0, y0 = np.floor(fx), np.floor(fyy)
    tx, ty = fx - x0, fyy - y0
    x0, y0 = x0.astype(np.int64), y0.astype(np.int64)
    val = g.sample(flip(src, up_flip), U, V) * F32(w)
    img = np.zeros((r, r, 4))
    for ox, oy, wt in ((0, 0, (1 - tx) * (1 - ty)), (1, 0, tx * (1 - ty)),
                       (0, 1, (1 - tx) * ty), (1, 1, tx * ty)):
        px, py = x0 + ox, y0 + oy
        ok = centre_in & (px >= 0) & (px < r) & (py >= 0) & (py < r)
        flat = (py * r + px)[ok]
        for c in range(4):
            img[..., c] += np.bincount(flat, weights=(val[..., c] * wt)[ok].astype(np.float64),
                                       minlength=r * r).reshape(r, r)
    return flip(img, out_flip).astype(F32)


def combos():
    return [(u, o) for u in (False, True) for o in (False, True)]


def rel_err(a, b, ch=slice(0, 3)):
    a, b = a[..., ch].astype(np.float64), b[..., ch].astype(np.float64)
    return float(np.abs(a - b).mean() / max(np.abs(b).mean(), 1e-12))


# ------------------------------------------------------------------ test inputs
def gradient_src(n=TEX):
    nx, ny, _, _ = g.grid(n, n)
    a = np.zeros((n, n, 4), F32)
    a[..., 0], a[..., 1], a[..., 2], a[..., 3] = nx, ny, nx * ny, 1.0
    return a


def uniform_field(fx, fy, n=TEX):
    a = np.zeros((n, n, 4), F32)
    a[..., 0], a[..., 1], a[..., 3] = fx / 2 + 0.5, fy / 2 + 0.5, 1.0
    return a


def white(n=TEX):
    return np.ones((n, n, 4), F32)


def stage_s0_s0b():
    print("\n== S0 / S0b: identity and orientation ==")
    src, fld = gradient_src(), uniform_field(0.3, 0.5)
    result, out = run(src, fld, [["d", 0.25], ["weight", 1.0]])
    report(result, "S0/S0b")
    if "base" not in out or "bypassed" not in out:
        print("  FAIL: captures missing", list(out))
        return None
    base, shifted = out["base"], out["bypassed"]
    print(f"  base capture: shape {base.shape}, mean RGB {base[..., :3].mean(axis=(0, 1)).round(3)}, "
          f"max {base[..., :3].max():.3f}")
    print("  S0 identity (d=0, n=256, weight=1): relative error vs NumPy emulation, per (up_flip, out_flip):")
    for u, o in combos():
        print(f"     up={int(u)} out={int(o)}  rel_err = "
              f"{rel_err(base, ref_scatter(src, fld, 0.0, 256, 1.0, u, o)):.4f}")
    print("  S0b shift (d=0.25, F=(0.3,0.5), n=256):")
    best, errs = None, {}
    for u, o in combos():
        e = errs[(u, o)] = rel_err(shifted, ref_scatter(src, fld, 0.25, 256, 1.0, u, o))
        print(f"     up={int(u)} out={int(o)}  rel_err = {e:.4f}")
        if best is None or e < errs[best]:
            best = (u, o)
    second = sorted(errs.values())[1]
    print(f"  best = up_flip {int(best[0])}, out_flip {int(best[1])} "
          f"(error {errs[best]:.4f} vs runner-up {second:.4f}: "
          f"{'distinct' if second > 3 * max(errs[best], 1e-4) else 'AMBIGUOUS'})")
    return best


def stage_s1(flips):
    print("\n== S1: float32 accumulation (4096 points, one pixel) ==")
    up, out_flip = flips
    n, tx, ty = 64, (100 + 0.5) / R, (150 + 0.5) / R          # target at a pixel centre
    nx, ny, _, _ = g.grid(TEX, TEX)
    gl_field = np.zeros((TEX, TEX, 4), F32)                    # F(u) = T - u, in GL space, d = 1
    gl_field[..., 0] = (tx - nx) / 2 + 0.5
    gl_field[..., 1] = (ty - ny) / 2 + 0.5
    gl_field[..., 3] = 1.0
    field_matrix = flip(gl_field, up)                          # matrix whose upload is gl_field
    result, out = run(white(), field_matrix, [["n", n], ["d", 1.0], ["weight", 1.0]])
    report(result, "S1")
    if "bypassed" not in out:
        print("  FAIL: capture missing")
        return
    img = out["bypassed"][..., 0]
    pk = np.unravel_index(np.argmax(img), img.shape)
    expect_row = (R - 1 - 150) if out_flip else 150
    print(f"  peak value {img.max():.1f} at (row {pk[0]}, col {pk[1]}); expected {n * n} at "
          f"(row {expect_row}, col 100); total over image {img.sum():.1f}")
    verdict = "PASS: float32 accumulates beyond 1.0" if img.max() > 1.5 else "FAIL: clamped near 1"
    exact = abs(float(img.max()) - n * n) < 0.5
    print(f"  {verdict}; peak {'equals' if exact else 'does NOT equal'} N^2 exactly")
    mult = float(img.sum()) / (n * n)
    print(f"  point multiplicity (total / N^2) = {mult:.4f}"
          f"{'' if abs(mult - 1) < 1e-3 else '  <-- NOT 1: the drawable emits each vertex more than once; weight must be divided by this'}")
    return mult


def stage_s2(flips, mult=1.0, fracs=(0.6, 1.0, 3.5)):
    print("\n== S2: real glass field vs NumPy scatter and photon-counting truth ==")
    n = int(os.environ.get("SPIKE_N", "1536"))
    w = (R / n) ** 2 / mult
    fy = -1.0 if tuple(flips) == (True, True) else 1.0
    print(f"  n={n}, weight={w:.5f} (multiplicity {mult:.3f}), fy={fy:+.0f} (flips {flips})")
    tex, dstar = cf.field_texture(), cf.first_fold_distance()
    tex512 = np.asarray(tex, F32)
    rows = []
    for fr in fracs:
        d = fr * dstar
        result, out = run(white(), tex512, [["n", n], ["d", d], ["weight", w], ["fy", fy]])
        report(result, f"S2 d={fr}d*")
        if "bypassed" not in out:
            print("  FAIL: capture missing")
            continue
        gpu = out["bypassed"]
        ref_found = ref_scatter(white(), tex512, d, n, w, *flips, fy=fy)
        ref_phys = ref_scatter(white(), tex512, d, n, w, False, False, fy=1.0)
        truth = cf.truth(d)
        mask = cf.interior(d)
        modl = cf.down(cf.module_caustic(tex512, cf.white(), d))
        a = gpu[..., 0].astype(np.float64)
        row = {"d": fr,
               "sum": (float(a.sum()), float(ref_found[..., 0].sum())),
               "r_vs_ref_found": cf.pearson(a[mask], ref_found[..., 0][mask]),
               "r_vs_ref_physical": cf.pearson(a[mask], ref_phys[..., 0][mask]),
               "r_vs_truth": cf.pearson(a[mask], truth[mask]),
               "iou_vs_truth": cf.top_iou(a[mask], truth[mask]),
               "r_module_vs_truth": cf.pearson(modl[mask], truth[mask]),
               "iou_module_vs_truth": cf.top_iou(modl[mask], truth[mask]),
               "max": float(a.max())}
        rows.append((row, a, ref_found[..., 0], truth, modl))
        print(f"  d={fr}d*: sum GPU {row['sum'][0]:.0f} vs ref {row['sum'][1]:.0f} | "
              f"r(GPU, NumPy scatter, detected flips) = {row['r_vs_ref_found']:.4f} | "
              f"r(GPU, NumPy scatter, physical convention) = {row['r_vs_ref_physical']:.4f}")
        print(f"          r(GPU, truth) = {row['r_vs_truth']:.3f}, top-8% IoU {row['iou_vs_truth']:.3f}   "
              f"[module mirror: r {row['r_module_vs_truth']:.3f}, IoU {row['iou_module_vs_truth']:.3f}]   "
              f"peak value {row['max']:.2f}")
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        names = ["truth (photon count)", "GPU scatter", "NumPy scatter", "module (gather)"]
        fig, ax = plt.subplots(4, len(rows), figsize=(2.2 * len(rows), 8.8), squeeze=False)
        for c, (row, a, rf, tr, md) in enumerate(rows):
            for r_, img in enumerate((tr, a, rf, md)):
                ax[r_, c].imshow(img, cmap="inferno", vmin=0, vmax=np.percentile(img, 99.5))
                ax[r_, c].set_xticks([])
                ax[r_, c].set_yticks([])
                if r_ == 0:
                    ax[r_, c].set_title(f"d = {row['d']} d*")
                if c == 0:
                    ax[r_, c].set_ylabel(names[r_], fontsize=8)
        fig.tight_layout()
        fp = HERE.parent / "scratch" / "scatter_spike_s2.png"
        fig.savefig(fp, dpi=70)
        print(f"  figure: {fp}")
    except ImportError:
        pass


def stage_s3_cost(flips):
    """Frame-period slope: the bench paces at ~16.7 ms (60 fps), so a result near that only says
    'within budget'; the slope rises once the GPU needs longer. Two job lengths per config
    (settle 12 and 60: 144 frames apart) cancel the one-off lattice build."""
    print("\n== S3a: cost (ms per frame from the slope between two job lengths; cap ~16.7) ==")
    dstar = cf.first_fold_distance()
    tex512 = np.asarray(cf.field_texture(), F32)
    nx, ny, _, _ = g.grid(TEX, TEX)
    tx, ty = (100 + 0.5) / R, (150 + 0.5) / R                  # worst case: every point on one pixel
    gl = np.zeros((TEX, TEX, 4), F32)
    gl[..., 0], gl[..., 1], gl[..., 3] = (tx - nx) / 2 + 0.5, (ty - ny) / 2 + 0.5, 1.0
    worst = flip(gl, flips[0])
    cases = [("glass 3.5d*", tex512, 3.5 * dstar, -1.0 if tuple(flips) == (True, True) else 1.0),
             ("worst: all points on one pixel", worst, 1.0, 1.0)]
    configs = [(64, 256), (1024, 256), (2048, 256), (1024, 1024), (2048, 1024), (2560, 1024)]
    for label, fld, d, fy in cases:
        print(f"  -- {label}")
        for n, r in configs:
            params = [["n", n], ["r", r], ["d", d], ["weight", 1.0], ["fy", fy]]
            try:
                (r1, _), (r2, _) = run(white(), fld, params, settle=12), run(white(), fld, params, settle=60)
            except Exception as e:                              # a stall or timeout is a result too
                print(f"     n={n:5d} ({n * n / 1e6:5.2f} M points) capture {r}x{r}: FAILED {type(e).__name__}: {e}")
                continue
            df = r2["frames_rendered"] - r1["frames_rendered"]
            ms = (r2["elapsed_ms"] - r1["elapsed_ms"]) / df if df > 0 else float("nan")
            errs = len(r1.get("errors") or []) + len(r2.get("errors") or [])
            print(f"     n={n:5d} ({n * n / 1e6:5.2f} M points) capture {r:4d}^2: {ms:6.2f} ms/frame"
                  f"{'  (at the 60 fps cap)' if ms < 17.5 else '  <-- over budget'}   errors {errs}")


def stage_s2b_density(flips, mult=1.0, fracs=(1.0, 3.5), ns=(256, 384, 512, 768, 1024, 1536)):
    """Quality vs point density: how many points per pixel does the caustic need?"""
    print("\n== S2b: quality vs point density (capture 256^2; points per pixel = n^2 / 256^2) ==")
    fy = -1.0 if tuple(flips) == (True, True) else 1.0
    dstar = cf.first_fold_distance()
    tex512 = np.asarray(cf.field_texture(), F32)
    for fr in fracs:
        d = fr * dstar
        truth, mask = cf.truth(d), cf.interior(d)
        print(f"  -- d = {fr} d*   (photon-count truth has ~144 samples/bin: its own noise limits r to ~0.99+)")
        for n in ns:
            w = (R / n) ** 2 / mult
            result, out = run(white(), tex512, [["n", n], ["d", d], ["weight", w], ["fy", fy]])
            if "bypassed" not in out:
                print(f"     n={n:5d}: capture missing")
                continue
            a = out["bypassed"][..., 0].astype(np.float64)
            print(f"     n={n:5d}  {n * n / R ** 2:5.1f} pts/px  {n * n / 1e6:5.2f} M pts:  "
                  f"r(GPU, truth) = {cf.pearson(a[mask], truth[mask]):.4f}   "
                  f"top-8% IoU = {cf.top_iou(a[mask], truth[mask]):.3f}   peak {a.max():.1f}")


def stage_s3b_lag(flips, jobs=8):
    """Same-frame ordering. spike_scatter_chain.maxpat runs an upstream pix whose uniform field encodes a
    free-running frame counter c (0..39) as F.x = 0.0125 * c. In ONE capture we read c back from (a) that
    pix, (b) a plain pix->pix reference, (c) the scatter output, whose mean shifts with the field it
    actually used (decoded through the NumPy emulation). The differences are the relative lags, in frames."""
    print("\n== S3b: frame lag of pix -> node(mesh) -> capture vs pix -> pix (counter decode) ==")
    fy = -1.0 if tuple(flips) == (True, True) else 1.0
    n, d = 512, 0.25
    w = (R / n) ** 2
    src, fld = gradient_src(), uniform_field(0.0, 0.0)
    m = slice(40, 216)
    cal = np.array([float(ref_scatter(src, uniform_field(0.0125 * c, 0.0), d, n, w, flips[0], flips[1],
                                      fy=fy)[m, m, 0].mean()) for c in range(40)])
    print(f"  decode table: mean R of the scatter for c = 0, 1, 39: {cal[0]:.4f}, {cal[1]:.4f}, {cal[39]:.4f}"
          f" (step {cal[1] - cal[0]:+.5f} per frame; the capture noise floor is far below that)")

    def wrap(v):                                     # counter differences, modulo 40, into -20..19
        return int((v + 20) % 40 - 20)

    lags_sc, lags_ref = [], []
    for k in range(jobs):
        params = [["n", n], ["d", d], ["weight", w], ["fy", fy]]
        result, out = run(src, fld, params, settle=6, warmup=30 + k, module="spike_scatter_chain.maxpat",
                          n_out=3, multi=True)
        report(result, f"S3b job {k}")
        o = out.get("bypassed")
        if not o or not all(i in o for i in (1, 2, 3)):
            print("     FAIL: captures missing", None if not o else sorted(o))
            continue
        c_sc = int(np.argmin(np.abs(cal - float(o[1][m, m, 0].mean()))))
        c_up = int(round(2 * (float(o[2][..., 0].mean()) - 0.5) / 0.0125))
        c_ref = int(round(2 * (float(o[3][..., 0].mean()) - 0.5) / 0.0125))
        lags_sc.append(wrap(c_up - c_sc))
        lags_ref.append(wrap(c_up - c_ref))
        print(f"     job {k}: counter seen by upstream pix = {c_up:2d}, by pix->pix reference = {c_ref:2d}, "
              f"by scatter output = {c_sc:2d}   -> lag vs upstream pix: reference {lags_ref[-1]:+d}, scatter {lags_sc[-1]:+d} frames")
    if lags_sc:
        print(f"  summary over {len(lags_sc)} captures: pix->pix reference lag values {sorted(set(lags_ref))}; "
              f"scatter lag values {sorted(set(lags_sc))} (frames behind the upstream pix)")


CAP_MS = 1000.0 / 60.0          # the bench's frame pacing: a pass cheaper than this is invisible to it


def _period_ms(n, r, d, fy, psize, snap=0.0, h=1.0, reps=1):
    """Frame period in ms (one scatter pass, one mesh): slope between a short and a long job, which
    cancels the one-off lattice build. Returns (list of ms per rep, total errors). Values at or under
    the cap only mean 'within budget'; above it they are the pass's real cost."""
    params = [["r", r], ["psize", psize], ["snap", snap], ["h", h], ["d", d],
              ["weight", (r / n) ** 2], ["fy", fy], ["n", n]]
    out, errs = [], 0
    for _ in range(reps):
        r1, _o1 = run(white(), TEX_FIELD, params, settle=12, timeout_ms=300000, warmup=12)
        r2, _o2 = run(white(), TEX_FIELD, params, settle=48, timeout_ms=300000, warmup=12)
        df = r2["frames_rendered"] - r1["frames_rendered"]
        out.append((r2["elapsed_ms"] - r1["elapsed_ms"]) / df if df > 0 else float("nan"))
        errs += len(r1.get("errors") or []) + len(r2.get("errors") or [])
    return out, errs


def stage_s4_sweep(flips):
    """S4: cost of ONE pass above the 60 fps cap, by raising the lattice size n in a single mesh.
    Density is at its worst here (up to 16 points per pixel), so ms per million points is a conservative
    upper bound for lower densities. Two variants: the current size-3 footprint, and corner-snapped size 2."""
    global TEX_FIELD
    TEX_FIELD = np.asarray(cf.field_texture(), F32)
    fy = -1.0 if tuple(flips) == (True, True) else 1.0
    d = 3.5 * cf.first_fold_distance()
    print(f"\n== S4: one-pass cost above the cap (single mesh; cap {CAP_MS:.1f} ms; glass at 3.5 d*; 48 B/vertex) ==")
    variants = [("size-3 footprint     ", 3, 0.0), ("corner-snap, size 2  ", 2, 1.0)]
    grid = [(512, (1536, 2048, 2560, 3072)), (1024, (2560, 3072, 3584, 4096))]
    fits = {}
    for label, psize, snap in variants:
        for r, ns in grid:
            pts = []
            for n in ns:
                try:
                    (ms,), e = _period_ms(n, r, d, fy, psize, snap)
                except Exception as ex:                    # a stall or timeout is itself a result
                    print(f"  {label} r={r:4d} n={n:5d} ({n * n / 1e6:5.2f} M pts): FAILED {type(ex).__name__}: {ex}")
                    continue
                over = ms > CAP_MS * 1.08
                pts.append((n * n / 1e6, ms, over))
                print(f"  {label} r={r:4d} n={n:5d} ({n * n / 1e6:5.2f} M pts, {n * n / r / r:4.1f} pts/px, "
                      f"{n * n * 48 / 1e6:5.0f} MB): {ms:7.2f} ms/frame  "
                      f"{'' if over else '(at the cap: within budget, cost unknown)'}  errors {e}", flush=True)
            above = [(m, t) for m, t, o in pts if o]
            if len(above) >= 2:
                m = np.array([a[0] for a in above])
                t = np.array([a[1] for a in above])
                slope = float(np.polyfit(m, t, 1)[0])
                fits[(label, r)] = slope
                print(f"     -> {label} r={r}: slope over the cap = {slope:.2f} ms per million points "
                      f"({len(above)} points)")
    print("\n  projection (slope x points; conservative, the slope was measured at 9-16 pts/px):")
    for (label, r), slope in fits.items():
        row = ", ".join(f"{ppp} pts/px at 1080p ({2.07 * ppp:.1f} M): {slope * 2.07 * ppp:.1f} ms" for ppp in (1, 2, 4))
        print(f"    {label} (fit at r={r}): {row}")
    print("\n  noise check, same config three times (size-3, r=1024, n=3072):")
    ms3, e = _period_ms(3072, 1024, d, fy, 3, 0.0, reps=3)
    print("    " + ", ".join(f"{v:.2f}" for v in ms3) + f" ms   errors {e}")
    run(white(), TEX_FIELD, [["n", 64]], settle=6)             # release the big lattice


def stage_s6_density(flips):
    """S6: separate vertex, fill and contention. n is FIXED at 4096 (16.8 M points, above the cap even
    at low density) and only the capture size r varies: 64 / 16 / 4 / 1 points per pixel. psize 1 draws
    the same vertices with ~1 fragment each, so it isolates vertex cost. Each config twice (noise ~15%)."""
    global TEX_FIELD
    TEX_FIELD = np.asarray(cf.field_texture(), F32)
    fy = -1.0 if tuple(flips) == (True, True) else 1.0
    d = 3.5 * cf.first_fold_distance()
    n = 4096
    mpts = n * n / 1e6
    print(f"\n== S6: fixed n={n} ({mpts:.1f} M points); capture size varies; ms per frame, 2 reps each ==")
    rows = [("size-3 footprint", 3, 0.0, r) for r in (512, 1024, 2048, 4096)]
    rows += [("corner-snap, size 2", 2, 1.0, r) for r in (512, 1024, 2048, 4096)]
    rows += [("size 1 (vertex only; energy wrong)", 1, 0.0, r) for r in (1024, 4096)]
    for label, psize, snap, r in rows:
        try:
            ms, e = _period_ms(n, r, d, fy, psize, snap, reps=2)
        except Exception as ex:
            print(f"  {label:36s} r={r:4d} ({n * n / r / r:5.1f} pts/px): FAILED {type(ex).__name__}: {ex}", flush=True)
            continue
        m = float(np.mean(ms))
        print(f"  {label:36s} r={r:4d} ({n * n / r / r:5.1f} pts/px): {ms[0]:6.2f} {ms[1]:6.2f}  mean {m:6.2f} ms "
              f"= {m / mpts:4.2f} ms per M pts{'  (at/near the cap)' if m < CAP_MS * 1.15 else ''}  errors {e}", flush=True)
    run(white(), TEX_FIELD, [["n", 64], ["r", 256]], settle=6)   # release the big lattice and capture


def box_down(img, f):
    h, w = img.shape
    return img.reshape(h // f, f, w // f, f).mean(axis=(1, 3))


def upscale(img, s):
    """Bilinear upscale by an integer factor, pixel centres aligned (output i <-> capture (i+.5)/s-.5)."""
    if s == 1:
        return img
    h = img.shape[0]
    x = np.clip((np.arange(h * s) + 0.5) / s - 0.5, 0, h - 1)
    i0 = np.floor(x).astype(int)
    i1 = np.minimum(i0 + 1, h - 1)
    t = x - i0
    a = img[i0] * (1 - t)[:, None] + img[i1] * t[:, None]
    return a[:, i0] * (1 - t)[None, :] + a[:, i1] * t[None, :]


def stage_s7_coarse(flips):
    """S7: what does a COARSE internal capture cost in quality? Reference = 16 pts/px scatter at 1024^2.
    Candidates: capture at 1024/s, 1/2/4 points per CAPTURE pixel, bilinear upscale to 1024. Metrics
    (interior mask, as in S2): Pearson r and top-8% IoU vs the reference at 1024 and after box-down to
    256, and vs the photon-counting truth at 256. Footprint: corner-snap + size 2 (identical image to
    size 3, S5). No timing here (these configs sit under the 60 fps cap); cost comes from S6's ms/M pts."""
    print("\n== S7: coarse capture + bilinear upscale vs a 16 pts/px reference at 1024^2 ==")
    fy = -1.0 if tuple(flips) == (True, True) else 1.0
    tex512 = np.asarray(cf.field_texture(), F32)
    dstar = cf.first_fold_distance()
    R_OUT = 1024
    keep = {}
    for fr in (1.0, 3.5):
        d = fr * dstar
        truth, mask = cf.truth(d), cf.interior(d)
        mask_hi = np.kron(mask, np.ones((R_OUT // 256, R_OUT // 256), bool))

        def capture(r, n):
            params = [["r", r], ["psize", 2], ["snap", 1.0], ["h", 1.0], ["d", d],
                      ["weight", (r / n) ** 2], ["fy", fy], ["n", n]]
            result, out = run(white(), tex512, params, timeout_ms=300000)
            if "bypassed" not in out:
                raise RuntimeError(f"capture missing (status {result.get('status')})")
            return out["bypassed"][..., 0].astype(np.float64)

        ref = capture(R_OUT, 4 * R_OUT)
        ref256 = box_down(ref, R_OUT // 256)
        print(f"  -- d = {fr} d*   reference (n=4096, 16 pts/px): r vs truth {cf.pearson(ref256[mask], truth[mask]):.4f}, "
              f"top-8% IoU {cf.top_iou(ref256[mask], truth[mask]):.3f}, peak {ref.max():.1f}")
        print("     s  capture  pts/px(cap)   M pts @1080p-equiv  | vs ref @1024: r / IoU | vs ref @256: r / IoU | vs truth @256: r / IoU")
        for sc in (1, 2, 4):
            r = R_OUT // sc
            for ppp in (1, 2, 4):
                n = int(round(r * ppp ** 0.5))
                try:
                    up = upscale(capture(r, n), sc)
                except Exception as ex:
                    print(f"     {sc}  {r:5d}^2  {ppp}: FAILED {type(ex).__name__}: {ex}", flush=True)
                    continue
                up256 = box_down(up, R_OUT // 256)
                keep[(fr, sc, ppp)] = up
                mpts = ppp * (1920 * 1080) / (sc * sc) / 1e6
                print(f"     {sc}  {r:5d}^2  {ppp:4d}          {mpts:6.2f}             | "
                      f"{cf.pearson(up[mask_hi], ref[mask_hi]):.4f} / {cf.top_iou(up[mask_hi], ref[mask_hi]):.3f}      | "
                      f"{cf.pearson(up256[mask], ref256[mask]):.4f} / {cf.top_iou(up256[mask], ref256[mask]):.3f}     | "
                      f"{cf.pearson(up256[mask], truth[mask]):.4f} / {cf.top_iou(up256[mask], truth[mask]):.3f}", flush=True)
        keep[(fr, "ref")] = ref
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        for fr in (1.0, 3.5):
            if (fr, "ref") not in keep:
                continue
            cols = [("reference 16/px", keep[(fr, "ref")])]
            for sc, ppp in ((1, 4), (2, 4), (2, 1), (4, 4), (4, 1)):
                if (fr, sc, ppp) in keep:
                    cols.append((f"s={sc}, {ppp}/px", keep[(fr, sc, ppp)]))
            fig, ax = plt.subplots(2, len(cols), figsize=(2.6 * len(cols), 5.4), squeeze=False)
            vmax = np.percentile(keep[(fr, "ref")], 99.5)
            for c, (name, img) in enumerate(cols):
                ax[0, c].imshow(img, cmap="inferno", vmin=0, vmax=vmax)
                ax[0, c].set_title(name, fontsize=8)
                ax[1, c].imshow(img[384:640, 384:640], cmap="inferno", vmin=0, vmax=vmax)   # 256^2 crop, 1:1
                for r_ in (0, 1):
                    ax[r_, c].set_xticks([])
                    ax[r_, c].set_yticks([])
            ax[0, 0].set_ylabel("full 1024^2", fontsize=8)
            ax[1, 0].set_ylabel("centre crop 1:1", fontsize=8)
            fig.tight_layout()
            fp = HERE.parent / "scratch" / f"scatter_spike_s7_{str(fr).replace('.', 'p')}dstar.png"
            fig.savefig(fp, dpi=80)
            print(f"  figure: {fp}")
    except ImportError:
        pass
    run(white(), tex512, [["n", 64], ["r", 256]], settle=6)       # release the big lattice and capture


def structure_score(e, region):
    """Periodic-structure score of a residual image: log10(max / median) of its power spectrum, over the
    region where `region` is True (the rest zeroed), low frequencies excluded. White noise gives about
    log10(20) = 1.3; a lattice moire concentrates power in a few bins and scores several decades higher."""
    x = np.where(region, e - e[region].mean(), 0.0)
    pw = np.abs(np.fft.fft2(x)) ** 2
    h = x.shape[0]
    fy_, fx_ = np.meshgrid(np.fft.fftfreq(h) * h, np.fft.fftfreq(h) * h, indexing="ij")
    ring = np.hypot(fy_, fx_) > 8
    v = pw[ring]
    return float(np.log10(v.max() / max(np.median(v), 1e-30)))


def stage_s8_jitter(flips):
    """S8: does jittering the lattice (hash offset within each point's own cell) turn the coarse-capture
    moire into plain noise? Reference = 16 pts/px, unjittered, 1024^2 (as S7). Per config, jit 0 vs 1:
    r / IoU vs the reference at 1024, RMS residual in the dim region relative to its mean, and the
    spectral structure score of that residual (lower = less periodic; ~1.3 = white noise)."""
    print("\n== S8: lattice jitter vs moire (reference 16 pts/px, 1024^2, unjittered) ==")
    fy = -1.0 if tuple(flips) == (True, True) else 1.0
    tex512 = np.asarray(cf.field_texture(), F32)
    dstar = cf.first_fold_distance()
    R_OUT = 1024
    keep = {}
    for fr in (3.5, 1.0):
        d = fr * dstar
        mask = cf.interior(d)
        mask_hi = np.kron(mask, np.ones((R_OUT // 256, R_OUT // 256), bool))

        def capture(r, n, jit):
            params = [["r", r], ["psize", 2], ["snap", 1.0], ["h", 1.0], ["d", d], ["jit", jit],
                      ["latn", n], ["weight", (r / n) ** 2], ["fy", fy], ["n", n]]
            result, out = run(white(), tex512, params, timeout_ms=300000)
            if "bypassed" not in out:
                raise RuntimeError(f"capture missing (status {result.get('status')})")
            return out["bypassed"][..., 0].astype(np.float64)

        ref = capture(R_OUT, 4 * R_OUT, 0.0)
        dim = mask_hi & (ref < 0.3 * ref[mask_hi].mean())
        print(f"  -- d = {fr} d*   (dim region = {100 * dim.sum() / mask_hi.sum():.0f}% of the interior)")
        print("     s  pts/px  jit | vs ref @1024: r / IoU | dim-region RMS residual / mean | structure score (white noise ~1.3)")
        for sc, ppp in ((1, 1), (2, 1), (2, 2), (4, 1), (4, 2)):
            r = R_OUT // sc
            n = int(round(r * ppp ** 0.5))
            for jit in (0.0, 1.0):
                try:
                    up = upscale(capture(r, n, jit), sc)
                except Exception as ex:
                    print(f"     {sc}  {ppp}  {jit}: FAILED {type(ex).__name__}: {ex}", flush=True)
                    continue
                keep[(fr, sc, ppp, jit)] = up
                e = up - ref
                rms = float(np.sqrt((e[dim] ** 2).mean()) / max(ref[dim].mean(), 1e-12))
                print(f"     {sc}  {ppp:4d}   {jit:3.1f} |    {cf.pearson(up[mask_hi], ref[mask_hi]):.4f} / "
                      f"{cf.top_iou(up[mask_hi], ref[mask_hi]):.3f}          |        {rms:6.3f}                |"
                      f"        {structure_score(e, dim):5.2f}", flush=True)
        keep[(fr, "ref")] = ref
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        for fr in (3.5, 1.0):
            if (fr, "ref") not in keep:
                continue
            cols = [("reference", keep[(fr, "ref")])]
            for sc, ppp, jit in ((2, 1, 0.0), (2, 1, 1.0), (2, 2, 0.0), (2, 2, 1.0), (4, 2, 0.0), (4, 2, 1.0)):
                if (fr, sc, ppp, jit) in keep:
                    cols.append((f"s={sc}, {ppp}/px, jit {jit:g}", keep[(fr, sc, ppp, jit)]))
            fig, ax = plt.subplots(1, len(cols), figsize=(2.9 * len(cols), 3.2), squeeze=False)
            vmax = np.percentile(keep[(fr, "ref")], 99.5)
            for c, (name, img) in enumerate(cols):
                ax[0, c].imshow(img[384:640, 384:640], cmap="inferno", vmin=0, vmax=vmax * 0.35)  # 1:1 crop, dim end stretched
                ax[0, c].set_title(name, fontsize=8)
                ax[0, c].set_xticks([])
                ax[0, c].set_yticks([])
            fig.tight_layout()
            fp = HERE.parent / "scratch" / f"scatter_spike_s8_{str(fr).replace('.', 'p')}dstar.png"
            fig.savefig(fp, dpi=80)
            print(f"  figure: {fp}")
    except ImportError:
        pass
    run(white(), tex512, [["n", 64], ["r", 256], ["jit", 0.0]], settle=6)   # release the lattice; jit back to 0


def gobo_sources(n=1024):
    """Fine-detail sources at n^2: a zone plate (frequency rises from 0 at the centre to Nyquist at the
    mid-edges) and checkerboards with 1, 3 and 8 px squares."""
    yy, xx = np.mgrid[0:n, 0:n].astype(np.float64)
    yc, xc = yy - (n - 1) / 2.0, xx - (n - 1) / 2.0
    out = {"zone plate": 0.5 + 0.5 * np.cos(np.pi * (xc ** 2 + yc ** 2) / n)}
    for sq in (1, 3, 8):
        out[f"checker {sq}px"] = (((xx // sq) + (yy // sq)) % 2).astype(np.float64)
    res = {}
    for k, v in out.items():
        a = np.ones((n, n, 4), F32)
        a[..., 0] = a[..., 1] = a[..., 2] = v.astype(F32)
        res[k] = a
    return res


def stage_s9_gobo(flips):
    """S9: source aliasing. The scatter reads the source once per lattice point, so a source finer than
    the lattice aliases. Reference = 16 pts/px at 1024^2 (lattice 4x finer than the 1024^2 source). Each
    candidate (lattice n < or = source size) is compared after box-down to 256^2 (what should survive of
    detail above the capture's Nyquist is its AVERAGE; low-frequency error there is aliasing), with 1 tap
    vs a 4-tap box prefilter in the vertex shader."""
    print("\n== S9: gobo / source aliasing (glass 3.5 d*; source 1024^2; compare after box-down to 256^2) ==")
    fy = -1.0 if tuple(flips) == (True, True) else 1.0
    tex512 = np.asarray(cf.field_texture(), F32)
    d = 3.5 * cf.first_fold_distance()
    mask = cf.interior(d)
    mask_hi = np.kron(mask, np.ones((4, 4), bool))
    R_OUT = 1024
    cfgs = [(1, 1), (2, 2), (4, 2)]           # (s, points per capture pixel): lattice n = 1024, 724, 362
    keep = {}
    for name, src in gobo_sources().items():
        def capture(r, n, taps):
            params = [["r", r], ["psize", 2], ["snap", 1.0], ["h", 1.0], ["d", d], ["jit", 0.0],
                      ["taps", taps], ["latn", n], ["weight", (r / n) ** 2], ["fy", fy], ["n", n]]
            result, out = run(src, tex512, params, timeout_ms=300000)
            if "bypassed" not in out:
                raise RuntimeError(f"capture missing (status {result.get('status')})")
            return out["bypassed"][..., 0].astype(np.float64)

        try:
            ref = capture(R_OUT, 4 * R_OUT, 1.0)
        except Exception as ex:
            print(f"  -- {name}: reference FAILED {type(ex).__name__}: {ex}", flush=True)
            continue
        ref256 = box_down(ref, 4)
        print(f"  -- {name}   (reference mean {ref[mask_hi].mean():.3f}, source mean {src[..., 0].mean():.3f})")
        print("     s  lattice n  taps | @256: r      rel RMS   | @1024: r")
        for sc, ppp in cfgs:
            r = R_OUT // sc
            n = int(round(r * ppp ** 0.5))
            for taps in (1.0, 4.0):
                try:
                    up = upscale(capture(r, n, taps), sc)
                except Exception as ex:
                    print(f"     {sc}  {n:5d}   {taps:g}: FAILED {type(ex).__name__}: {ex}", flush=True)
                    continue
                keep[(name, sc, taps)] = up
                u256 = box_down(up, 4)
                rms = float(np.sqrt(((u256 - ref256)[mask] ** 2).mean()) / max(ref256[mask].mean(), 1e-12))
                print(f"     {sc}  {n:5d}      {taps:g}  |   {cf.pearson(u256[mask], ref256[mask]):.4f}   {rms:7.3f}   |"
                      f"   {cf.pearson(up[mask_hi], ref[mask_hi]):.4f}", flush=True)
        keep[(name, "ref")] = ref
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        names = [k for k in gobo_sources() if (k, "ref") in keep]
        fig, ax = plt.subplots(len(names), 5, figsize=(13, 2.7 * len(names)), squeeze=False)
        for ri, name in enumerate(names):
            cols = [("reference", keep[(name, "ref")])]
            for sc, taps in ((2, 1.0), (2, 4.0), (4, 1.0), (4, 4.0)):
                if (name, sc, taps) in keep:
                    cols.append((f"s={sc}, {int(taps)} tap", keep[(name, sc, taps)]))
            vmax = np.percentile(keep[(name, "ref")], 99.5)
            for c, (title, img) in enumerate(cols):
                ax[ri, c].imshow(box_down(img, 2)[192:320, 192:320], cmap="gray", vmin=0, vmax=vmax)   # 1:2 crop
                ax[ri, c].set_title(f"{name}: {title}" if c == 0 else title, fontsize=7)
                ax[ri, c].set_xticks([])
                ax[ri, c].set_yticks([])
        fig.tight_layout()
        fp = HERE.parent / "scratch" / "scatter_spike_s9.png"
        fig.savefig(fp, dpi=75)
        print(f"  figure: {fp}")
    except ImportError:
        pass
    run(white(), tex512, [["n", 64], ["r", 256], ["taps", 1.0]], settle=6)


def resize_bilinear(img, H, W):
    """Bilinear resize of an (h, w, c) array to (H, W, c), pixel centres aligned (what sample(in1, norm) does
    when magnifying)."""
    h, w = img.shape[:2]
    ys = np.clip((np.arange(H) + 0.5) * h / H - 0.5, 0, h - 1)
    xs = np.clip((np.arange(W) + 0.5) * w / W - 0.5, 0, w - 1)
    y0, x0 = np.floor(ys).astype(int), np.floor(xs).astype(int)
    y1, x1 = np.minimum(y0 + 1, h - 1), np.minimum(x0 + 1, w - 1)
    ty, tx = (ys - y0)[:, None, None], (xs - x0)[None, :, None]
    a = img[y0][:, x0] * (1 - tx) + img[y0][:, x1] * tx
    b = img[y1][:, x0] * (1 - tx) + img[y1][:, x1] * tx
    return a * (1 - ty) + b * ty


def stage_s10_tone(flips):
    """S10: does the display stage (tone map + upscale, scratch/build_scatter_look.py) work behind the scatter?
    spike_scatter_tone.maxpat adds two copies of it to the node's output: outlet 1 with the live patch's
    attributes (@adapt 0 @dim 1920 1080), outlet 2 with default attributes. Reference: the NumPy tone curve
    applied to the raw capture (outlet 0) and bilinearly resized."""
    print("\n== S10: tone map + upscale stage behind the scatter (bench, known inputs) ==")
    fy = -1.0 if tuple(flips) == (True, True) else 1.0
    d = 1.0 * cf.first_fold_distance()
    r, n = 512, 724
    params = [["r", r], ["psize", 2], ["snap", 1.0], ["h", 1.0], ["jit", 0.0], ["taps", 1.0], ["latn", n],
              ["weight", (r / n) ** 2], ["fy", fy], ["d", d], ["n", n]]
    src = np.asarray(gradient_src(), F32)
    result, out = run(src, np.asarray(cf.field_texture(), F32), params, module="spike_scatter_tone.maxpat",
                      n_out=3, multi=True, timeout_ms=180000)
    report(result, "S10")
    o = out.get("bypassed")
    if not o or not all(k in o for k in (1, 2, 3)):
        print("  FAIL: captures missing:", None if not o else sorted(o))
        return
    raw = o[1].astype(np.float64)
    print(f"  raw capture (outlet 0): shape {raw.shape}, mean RGB {raw[..., :3].reshape(-1, 3).mean(0).round(4)}, "
          f"max {raw[..., :3].max():.3f}")
    for k, name in ((2, "live attrs (@adapt 0 @dim 1920 1080)"), (3, "default attrs")):
        t = o[k].astype(np.float64)
        ref = resize_bilinear(raw, t.shape[0], t.shape[1])[..., :3]
        ref = (ref / (1.0 + ref)) ** 0.7                      # lev = 1, expo = 0.7
        a, b = t[..., :3].ravel(), ref.ravel()
        r_ = float(np.corrcoef(a, b)[0, 1]) if a.std() > 0 and b.std() > 0 else float("nan")
        print(f"  tone, {name}: shape {t.shape}, mean RGB {t[..., :3].reshape(-1, 3).mean(0).round(4)}, "
              f"max {t[..., :3].max():.3f}, alpha mean {t[..., 3].mean():.3f}; "
              f"expected mean {b.mean():.4f}; Pearson vs NumPy {r_:.4f}, max |diff| {np.abs(a - b).max():.4f}")


DETAIL_STEPS = [(256, 2), (512, 2), (768, 2), (1024, 2), (1024, 4)]   # as make_spike_scatter.py's `detail` ladder


def stage_s11_detail(flips):
    """S11: `detail N` must set exactly what the equivalent hand-written parameter sequence sets: for each step,
    one job sends the individual messages and one sends `detail N`; the captures must be identical."""
    print("\n== S11: `detail N` against the equivalent explicit parameter messages ==")
    fy = -1.0 if tuple(flips) == (True, True) else 1.0
    d = 1.0 * cf.first_fold_distance()
    src, fld = np.asarray(gradient_src(), F32), np.asarray(cf.field_texture(), F32)
    for i, (r, ppp) in enumerate(DETAIL_STEPS, 1):
        n = int(round(r * ppp ** 0.5))
        w = float(f"{(r / n) ** 2:.4f}")                      # the patch's message boxes write 4 decimals
        manual = [["fy", fy], ["d", d], ["psize", 2], ["snap", 1.0], ["h", 1.0], ["jit", 0.0], ["taps", 1.0],
                  ["r", r], ["latn", n], ["weight", w], ["n", n]]
        via = [["fy", fy], ["d", d], ["detail", i]]
        res_a, out_a = run(src, fld, manual, timeout_ms=240000)
        res_b, out_b = run(src, fld, via, timeout_ms=240000)
        ea = len(res_a.get("errors") or []) + len(res_b.get("errors") or [])
        a, b = out_a.get("bypassed"), out_b.get("bypassed")
        if a is None or b is None:
            print(f"  step {i} ({r}^2, {ppp}/px, n={n}): FAIL capture missing (errors {ea})")
            continue
        diff = np.abs(a.astype(np.float64) - b.astype(np.float64))
        print(f"  step {i} ({r}^2, {ppp} pts/px, n={n}, {n * n / 1e6:5.2f} M pts): capture {b.shape[1]}x{b.shape[0]}, "
              f"max|diff| {diff.max():.6f}, mean RGB {b[..., :3].reshape(-1, 3).mean(0).round(3)}, errors {ea}"
              f"  {'IDENTICAL' if diff.max() == 0 else ''}", flush=True)
    run(white(), np.asarray(cf.field_texture(), F32), [["n", 64], ["r", 256]], settle=6)


def stage_s5_snap(flips):
    """S5: is the corner-snapped size-2 point the same image as the size-3 point? (n=1536 into 256^2.)
    Controls: size 2 WITHOUT snap should lose energy (round points: only centres within 1 px are covered)."""
    print("\n== S5: corner-snap + size 2 vs size 3 (identical image expected) ==")
    n = 1536
    w = (R / n) ** 2
    fy = -1.0 if tuple(flips) == (True, True) else 1.0
    d = 3.5 * cf.first_fold_distance()
    tex512 = np.asarray(cf.field_texture(), F32)
    imgs = {}
    for name, psize, snap in (("size3", 3, 0.0), ("snap+size2", 2, 1.0), ("size2 no snap", 2, 0.0),
                              ("snap+size3", 3, 1.0)):
        params = [["psize", psize], ["snap", snap], ["n", n], ["d", d], ["weight", w], ["fy", fy]]
        result, out = run(white(), tex512, params)
        report(result, name)
        if "bypassed" not in out:
            print("  FAIL: capture missing")
            return
        imgs[name] = out["bypassed"][..., 0].astype(np.float64)
    ref = imgs["size3"]
    inner = (slice(3, -3), slice(3, -3))
    for name, a in imgs.items():
        diff = np.abs(a - ref)
        print(f"  {name:14s} sum {a.sum():10.1f} (size3 {ref.sum():.1f}, ratio {a.sum() / ref.sum():.4f})  "
              f"max|diff| {diff.max():9.4f} (interior {diff[inner].max():9.4f})  "
              f"L1 diff / sum {diff.sum() / ref.sum():.5f}  peak {a.max():.2f} vs {ref.max():.2f}")


def main():
    ensure_bench()
    stages = sys.argv[1:] or ["s0", "s1", "s2"]
    flips = stage_s0_s0b()
    if flips is None:
        print("S0 failed: stopping")
        return
    mult = 1.0
    if "s1" in stages:
        mult = stage_s1(flips) or 1.0
    if "s2" in stages:
        stage_s2(flips, mult)
    if "s2b" in stages:
        stage_s2b_density(flips, mult)
    if "s3" in stages:
        stage_s3_cost(flips)
    if "s3b" in stages:
        stage_s3b_lag(flips)
    if "s5" in stages:
        stage_s5_snap(flips)
    if "s4" in stages:
        stage_s4_sweep(flips)
    if "s6" in stages:
        stage_s6_density(flips)
    if "s7" in stages:
        stage_s7_coarse(flips)
    if "s8" in stages:
        stage_s8_jitter(flips)
    if "s9" in stages:
        stage_s9_gobo(flips)
    if "s10" in stages:
        stage_s10_tone(flips)
    if "s11" in stages:
        stage_s11_detail(flips)


if __name__ == "__main__":
    main()
