"""
f_caustic -- definition. Two modes (.specify/f_caustic_scatter/spec.md, plan.md):
  soft    the 8-tap gather (codebox_v2.gen, UNCHANGED: the primary pix `caustic_pix`)
  sheets  a GPU forward scatter (a jit.gl.node capture + points mesh + package/code/f_caustic_sheets.jxs, raw boxes
          generated by scatter_scene.py into raw_ui.json), composited by `sheets` (codebox_sheets.gen)
Two select stages (one per outlet) pick a branch by a Param and apply bypass; the inactive branch is disabled.

Regenerate the raw layer BEFORE a build:   python3 src/f_caustic/scatter_scene.py
Build:                                     build/py.sh build/build_patcher.py src/f_caustic/definition.py
"""
import json
from pathlib import Path

_HERE = Path(__file__).resolve().parent
_RAW = json.loads((_HERE / "raw_ui.json").read_text()) if (_HERE / "raw_ui.json").exists() else {}

# raw box ids fixed by scatter_scene.py
SLAB_SRC = "obj-901"         # the scene's source slab
SLAB_FIELD = "obj-902"       # the scene's field slab

patcher = {
    "name":               "f_caustic",
    "prefix":             "caustic",
    "title":              "Caustic",
    "signal_type":        "vecfield",
    "archetype":          "processor",

    # Bypass drives the codebox Param `bypass_gate`, not the native @bypass, which skips the shader and flips secondary
    # outlets.  Every outlet mixes to its passthrough, so a bypassed module is a passthrough (Matt, 2026-10-05).
    # Here the soft stage keeps its own gate and each select stage applies it last (plan ADR-4).
    "bypass_mode":        "param",
    "bypass_target":      ["caustic", "select_comp", "select_layer"],

    "presentation_width":  227,
    "presentation_height": 122,

    # Two outlets, now fed by the select stages: composite and the isolated caustic layer
    "outlets": [
        {"comment": "composite"},
        {"comment": "caustic", "color": [0.6196078431372549, 0.9529411764705882, 0.6588235294117647, 1.0]},
    ],
    "outlet_source": {0: ["select_comp", 0], 1: ["select_layer", 0]},

    # Inlet 0 (texture + control): the light source reaches the soft stage, the sheets composite, both select stages
    # (for bypass) and the scene's source slab.  Inlet 1: the vecfield, direct (no vs_inState: unconnected = silent).
    "inlet_fanout": {"texture": [["caustic", 0], ["sheets", 0], ["select_comp", 2], ["select_layer", 2], [SLAB_SRC, 0]]},
    "mod_inlets": [
        {"label": "vecfield", "vs_instate": False,
         "fanout": [["caustic", 1], ["sheets", 2], [SLAB_FIELD, 0]]},
    ],

    "pix_chain": [
        # the soft path: the SAME codebox, name and attributes as the single-pix module had
        {"id": "caustic", "name": "caustic_pix", "gen": "codebox_v2.gen", "n_inlets": 2, "n_outlets": 2,
         "pix_type": "float32", "primary": True},
        # the sheets composite starts DISABLED (the mode network enables it); it follows its first input's size
        {"id": "sheets", "name": "#0_caustic_sheets", "gen": "codebox_sheets.gen", "n_inlets": 3, "n_outlets": 2,
         "pix_attrs": "@type float32 @adapt 1 @enable 0", "primary": False},
        {"id": "select_comp", "name": "#0_caustic_selc", "gen": "codebox_select_comp.gen", "n_inlets": 3,
         "n_outlets": 1, "pix_attrs": "@type float32 @adapt 1", "primary": False},
        {"id": "select_layer", "name": "#0_caustic_sell", "gen": "codebox_select_layer.gen", "n_inlets": 3,
         "n_outlets": 1, "pix_attrs": "@type float32 @adapt 1", "primary": False},
    ],
    "pix_wires": [
        ["caustic", 0, "select_comp", 0], ["caustic", 1, "select_layer", 0],
        ["sheets", 0, "select_comp", 1], ["sheets", 1, "select_layer", 1],
    ],

    "params": [
        {"name": "mix_pct",     "type": "float", "min": 0.0, "max": 100.0, "default": 0.0,  "label": "Mix", "widget": "numbox",
         "pix_target": ["caustic", "sheets"], "pix_shared_attrui": True,
         "hint": "Dry/wet crossfade toward the fully-composited (source+caustic) state. Renamed from strength 2026-07-12, range capped to true 0-100% (dropping the old 0-1.5 extrapolation zone). Internal Param named mix_pct to avoid colliding with the codebox's mix() operator."},
        {"name": "gain",        "type": "float", "min": 0.0, "max": 2.0, "default": 0.5,  "label": "Gain",
         "pix_target": ["caustic", "sheets"], "pix_shared_attrui": True,
         "hint": "Caustic brightness scale. Renamed from intensity 2026-07-12 to match the library-wide gain/mix naming convention. Both modes (the sheets mode applies an internal constant so the same value reads comparably)."},
        {"name": "scale",       "type": "float", "min": 0.0, "max": 1.0, "default": 0.3,  "label": "Scale",
         "hint": "Soft mode: the streamline trace distance. Sheets mode: the propagation distance of the scatter, in UV per unit field (sheets fold over at larger values)."},
        {"name": "softness",    "type": "float", "min": 0.0, "max": 1.0, "default": 0.3,  "label": "Soft",
         "hint": "Soft mode only (ignored in sheets mode)."},
        {"name": "color_shift", "type": "float", "min": 0.0, "max": 1.0, "default": 0.0,  "label": "Color",
         "hint": "Soft mode only (ignored in sheets mode)."},
        {"name": "mode",        "type": "menu", "options": ["Soft", "Sheets"], "default": 0, "label": "Mode",
         "pix_wire": False,      # no attrui: the menu's outlet feeds the mode network (scatter_scene.py)
         "hint": "Soft: the 8-tap gather (thin bright lines). Sheets: a GPU forward scatter that forms overlapping folded sheets at larger Scale."},
        {"name": "detail",      "type": "menu",
         "options": ["1: 256 sq 2/px", "2: 512 sq 2/px", "3: 768 sq 2/px", "4: 1024 sq 2/px", "5: 1024 sq 4/px"],
         "default": 4, "label": "Detail", "pix_wire": False,
         "hint": "Sheets mode: capture size and points per pixel (a quality / cost ladder; the output size does not change the cost). Changing it rebuilds the lattice: set it up, do not automate it."},
        {"name": "bypass",      "type": "bypass"},
    ],

    "raw_boxes":      _RAW.get("raw_boxes", []),
    "raw_lines":      _RAW.get("raw_lines", []),
    "raw_parameters": _RAW.get("raw_parameters", {}),
}


# BEGIN overrides (build/capture.py rewrites only this block)
patcher["overrides"] = {
    # the two menus sit on a row under the dials: Mode on the left, a wider Detail so its labels fit
    "mode.label": {"presentation_rect": [2.0, 84.0, 40.0, 18.0]},
    "mode.ctl": {"presentation_rect": [4.0, 101.0, 80.0, 15.0]},
    "detail.label": {"presentation_rect": [92.0, 84.0, 50.0, 18.0]},
    "detail.ctl": {"presentation_rect": [94.0, 101.0, 126.0, 15.0]},
}
# END overrides
