"""
f_caustic -- definition. Soft mode (the 8-tap gather) and the mode/detail menus were removed 2026-10-10: this is
now a single GPU forward-scatter path (a jit.gl.node capture + points mesh + package/code/f_caustic_sheets.jxs,
raw boxes generated by scatter_scene.py into raw_ui.json), always at the old "detail 5" step (1024 sq, 4 points
per capture pixel), composited by the chain's one pix stage, `caustic` (codebox_sheets.gen). See
docs/f-reference/f_caustic.md and the decision note in .specify/f_caustic_scatter/tasks.md.

Regenerate the raw layer BEFORE a build:   python3 src/f_caustic/scatter_scene.py
Build:                                     build/py.sh build/build_patcher.py src/f_caustic/definition.py
"""
import json
from pathlib import Path

_HERE = Path(__file__).resolve().parent
_RAW = json.loads((_HERE / "raw_ui.json").read_text()) if (_HERE / "raw_ui.json").exists() else {}

# raw box ids fixed by scatter_scene.py
SLAB_SRC = "obj-901"         # the scene's source slab
SLAB_FIELD = "obj-902"       # the scene's field slab

patcher = {
    "name":               "f_caustic",
    "prefix":             "caustic",
    "title":              "Caustic",
    "signal_type":        "vecfield",
    "archetype":          "processor",

    # Bypass drives the codebox Param `bypass_gate` (in codebox_sheets.gen itself now -- there is no second stage
    # left to apply it last), not the native @bypass, which skips the shader and flips secondary outlets. Every
    # outlet mixes to its passthrough, so a bypassed module is a passthrough (Matt, 2026-10-05).
    "bypass_mode":        "param",
    "bypass_target":      ["caustic"],

    "presentation_width":  227,
    "presentation_height": 122,

    # Two outlets, straight from the one pix stage: composite and the isolated caustic layer
    "outlets": [
        {"comment": "composite"},
        {"comment": "caustic", "color": [0.6196078431372549, 0.9529411764705882, 0.6588235294117647, 1.0]},
    ],
    "outlet_source": {0: ["caustic", 0], 1: ["caustic", 1]},

    # Inlet 0 (texture + control): the light source reaches the composite stage and the scene's source slab.
    # Inlet 1: the vecfield, direct (no vs_inState: unconnected = silent, not a misleading default caustic).
    "inlet_fanout": {"texture": [["caustic", 0], [SLAB_SRC, 0]]},
    "mod_inlets": [
        {"label": "vecfield", "vs_instate": False,
         "fanout": [["caustic", 2], [SLAB_FIELD, 0]]},
    ],

    "pix_chain": [
        {"id": "caustic", "name": "#0_caustic_sheets", "gen": "codebox_sheets.gen", "n_inlets": 3, "n_outlets": 2,
         "pix_attrs": "@type float32 @adapt 1", "primary": True},
    ],

    "params": [
        {"name": "mix_pct",     "type": "float", "min": 0.0, "max": 100.0, "default": 0.0,  "label": "Mix", "widget": "numbox",
         "hint": "Dry/wet crossfade toward the fully-composited (source+caustic) state. Renamed from strength 2026-07-12, range capped to true 0-100% (dropping the old 0-1.5 extrapolation zone). Internal Param named mix_pct to avoid colliding with the codebox's mix() operator."},
        {"name": "gain",        "type": "float", "min": 0.0, "max": 2.0, "default": 0.5,  "label": "Gain",
         "range_tiers": [0.1, 1.0, 2.0],
         "hint": "Caustic brightness scale. Renamed from intensity 2026-07-12 to match the library-wide gain/mix naming convention. The scatter applies an internal constant (k_sheets) so this reads comparably to the old soft-mode gain. Range menu added 2026-10-08 (Matt)."},
        {"name": "scale",       "type": "float", "min": 0.0, "max": 1.0, "default": 0.3,  "label": "Scale",
         "pix_wire": False,      # no attrui: `scale` drives the raw scene's control entry (scatter_scene.py),
                                 # not a Param on the composite codebox -- tapped directly at the dial's outlet
         "range_tiers": [1.0, 2.5],
         "hint": "The propagation distance of the scatter, in UV per unit field -- sheets fold over at larger values. Range menu added 2026-10-08 (Matt): default tier is the original 0-1, second tier opens 0-2.5; above 1.0 is less tested than the default range."},
        {"name": "expo",        "type": "float", "min": 0.3, "max": 1.5, "default": 0.7,  "label": "Expo",
         "hint": "Tone-curve exponent for the caustic layer's exposure curve, (v/(1+v))^expo -- lower compresses highlights harder, higher keeps more contrast. Was a fixed internal constant (0.7, the look-patch default) until 2026-10-10, now exposed."},
        {"name": "bypass",      "type": "bypass"},
    ],

    "raw_boxes":      _RAW.get("raw_boxes", []),
    "raw_lines":      _RAW.get("raw_lines", []),
    "raw_parameters": _RAW.get("raw_parameters", {}),
}


# BEGIN overrides (build/capture.py rewrites only this block)
patcher["overrides"] = {}
# END overrides
