"""
build_fluid_tuning.py -- generate ~/Vsynth/patterns/fluid_tuning.maxpat,
the tier-3 tuning harness for f_vf_fluid Phase 3 (T035).

Scratch patch, not committed, not part of the build system. Regenerate with:
    python3 scratch/build_fluid_tuning.py

Shape (see .specify/f_vf_fluid/tasks.md T035):
  force sources -> [switch 4] -> f_vf_fluid -> consumers -> [switch 5] -> vs_output

Notes for whoever reads this next:
  * vs_render already carries jit.fpsgui and routes `dim`, so the HD/4K
    switch and the fps readout for T041 are message boxes, not new machinery.
  * The unused force producers are NOT disabled -- f_ modules use the bypass
    toggle rather than Vsynth's `enable` convention. Measure Fluid's cost
    differentially instead: fps with Fluid's bypass on vs off.
  * `taps` only changes anything with a NOISY force. Use f_vf_optical_flow on
    video (vs_sources_main, movie tab). Vortex/flow/repulse are smooth by
    design and will show nothing -- that is what made T038a inconclusive.
"""
import json
from pathlib import Path

OUT = Path.home() / "Vsynth" / "patterns" / "fluid_tuning.maxpat"

boxes, lines = [], []


def bp(oid, name, n_in, n_out, rect, varname=None):
    """A Vsynth/f_ bpatcher. Texture outlets unless stated otherwise."""
    box = {"id": oid, "maxclass": "bpatcher", "name": name,
           "numinlets": n_in, "numoutlets": n_out,
           "patching_rect": [float(v) for v in rect],
           "bgmode": 1, "border": 1, "clickthrough": 0,
           "enablehscroll": 0, "enablevscroll": 0,
           "lockeddragscroll": 0, "lockedsize": 0,
           "offset": [0.0, 0.0], "viewvisibility": 1}
    if n_out:
        box["outlettype"] = ["jit_gl_texture"] * n_out
    if varname:
        box["varname"] = varname
    boxes.append({"box": box})


def obj(oid, text, n_in, n_out, rect, outlettype=None, varname=None):
    box = {"id": oid, "maxclass": "newobj", "text": text,
           "numinlets": n_in, "numoutlets": n_out,
           "patching_rect": [float(v) for v in rect]}
    if n_out:
        box["outlettype"] = outlettype or [""] * n_out
    if varname:
        box["varname"] = varname
    boxes.append({"box": box})


def msg(oid, text, rect):
    boxes.append({"box": {"id": oid, "maxclass": "message", "text": text,
                          "numinlets": 2, "numoutlets": 1, "outlettype": [""],
                          "patching_rect": [float(v) for v in rect]}})


def note(oid, text, rect, fontsize=None):
    box = {"id": oid, "maxclass": "comment", "text": text,
           "numinlets": 1, "numoutlets": 0,
           "patching_rect": [float(v) for v in rect]}
    if fontsize:
        box["fontsize"] = float(fontsize)
        box["fontface"] = 1
    boxes.append({"box": box})


def menu(oid, items, rect, varname=None):
    """umenu with comma-separated item list (Max's JSON form)."""
    entries = []
    for i, it in enumerate(items):
        if i:
            entries.append(",")
        entries.append(it)
    box = {"id": oid, "maxclass": "umenu", "items": entries,
           "numinlets": 1, "numoutlets": 3,
           "outlettype": ["int", "", ""],
           "parameter_enable": 0, "pattrmode": 1,
           "patching_rect": [float(v) for v in rect]}
    if varname:
        box["varname"] = varname
    boxes.append({"box": box})


def wire(s, so, d, di):
    lines.append({"patchline": {"source": [s, so], "destination": [d, di]}})


# ---------------------------------------------------------------- harness
note("t-title", "f_vf_fluid TUNING -- generated by scratch/build_fluid_tuning.py. "
     "Regenerating overwrites hand edits.", [25, 4, 780, 20], fontsize=13)

bp("vsmods", "vs_modules.maxpat", 0, 0, [25, 30, 79, 316])
bp("fmods", "f_modules.maxpat", 0, 0, [112, 30, 96, 249])
bp("render", "vs_render.maxpat", 1, 1, [220, 30, 97, 147], varname="vs_render")

note("t-dim", "render size (T041 / taps at 4K)", [220, 182, 220, 18])
msg("m-720", "dim 1280 720", [220, 202, 100, 22])
msg("m-1080", "dim 1920 1080", [220, 228, 100, 22])
msg("m-2160", "dim 3840 2160", [220, 254, 100, 22])
for m in ("m-720", "m-1080", "m-2160"):
    wire(m, 0, "render", 0)
note("t-fps", "fps readout is inside vs_render (jit.fpsgui).",
     [330, 202, 230, 34])

# content / dye texture for the consumers, and the repulse force source
bp("wfg", "vs_wfg_3.maxpat", 3, 2, [345, 30, 178, 132], varname="vs_wfg_3")
note("t-wfg", "content texture (dye)", [345, 166, 180, 18])

# video for f_vf_optical_flow -- the only NOISY force source
bp("src", "vs_sources_main.maxpat", 1, 1, [545, 30, 542, 442], varname="vs_sources")
note("t-src", "video source -- use the movie tab; this is what makes `taps` visible",
     [545, 476, 480, 18])


# ---------------------------------------------------------- force sources
note("t-force", "FORCE SOURCES  (1 Vortex  2 Flow  3 Repulse  4 Optical Flow)",
     [25, 510, 520, 20], fontsize=13)

bp("vortex", "f_vf_vortex.maxpat", 5, 1, [25, 534, 204, 160], varname="f_vf_vortex")
bp("flow", "f_vf_flow.maxpat", 1, 1, [245, 534, 158, 81], varname="f_vf_flow")
bp("repulse", "f_vf_repulse.maxpat", 1, 1, [245, 625, 172, 81], varname="f_vf_repulse")
bp("optflow", "f_vf_optical_flow.maxpat", 1, 2, [435, 534, 198, 143],
   varname="f_vf_optical_flow")

wire("wfg", 0, "repulse", 0)     # repulse needs a texture to push away from
wire("src", 0, "optflow", 0)     # optical flow needs real video motion

note("t-smooth", "vortex / flow / repulse are SMOOTH -- `taps` does nothing "
     "with these, by design", [25, 700, 400, 34])

menu("fsel", ["Vortex", "Flow", "Repulse", "Optical Flow"], [655, 534, 140, 22],
     varname="force_select")
obj("fsel1", "+ 1", 2, 1, [655, 562, 40, 22], ["int"])
obj("fswitch", "switch 4", 5, 1, [655, 590, 80, 22], ["jit_gl_texture"])
wire("fsel", 0, "fsel1", 0)
wire("fsel1", 0, "fswitch", 0)
for i, m in enumerate(("vortex", "flow", "repulse", "optflow")):
    wire(m, 0, "fswitch", i + 1)


# ----------------------------------------------------------------- fluid
note("t-fluid", "f_vf_fluid", [25, 750, 200, 20], fontsize=13)
bp("fluid", "f_vf_fluid.maxpat", 1, 1, [25, 790, 198, 150], varname="f_vf_fluid")
wire("fswitch", 0, "fluid", 0)

# Phase 2 defaults. Last session's tier-3 test was inconclusive partly because
# Fluid was left in an undamped, saturating state -- always start from here.
DEFAULTS = ("force 0.02, dt 0.01, viscosity 0.085, project 1., "
            "drag 0.5, gain 1., taps 8")
msg("m-reset", DEFAULTS, [245, 760, 440, 22])
note("t-reset", "^ RESET to Phase 2 defaults -- click before judging anything",
     [245, 784, 400, 18])

for i, t in enumerate(("taps 1", "taps 8", "taps 16")):
    msg("m-taps%d" % i, t, [245 + i * 70, 812, 62, 22])
note("t-taps", "T038a A/B", [460, 812, 100, 18])

for i, t in enumerate(("project 0.", "project 1.")):
    msg("m-proj%d" % i, t, [245 + i * 90, 844, 82, 22])
note("t-proj", "T037: 0 = Burgers-like shock fronts, 1 = divergence-free swirl",
     [430, 844, 420, 18])

for b in [x["box"]["id"] for x in boxes
          if x["box"]["id"].startswith(("m-reset", "m-taps", "m-proj"))]:
    wire(b, 0, "fluid", 0)


# ------------------------------------------------------------- consumers
note("t-cons", "CONSUMERS  (1 Advect  2 Warp  3 Glow  4 Field X  5 Raw field)",
     [25, 960, 520, 20], fontsize=13)

bp("advect", "f_vf_advect.maxpat", 2, 3, [25, 984, 198, 150], varname="f_vf_advect")
bp("warp", "f_vf_warp.maxpat", 2, 2, [245, 984, 106, 90], varname="f_vf_warp")
bp("glow", "f_vf_glow.maxpat", 3, 2, [375, 984, 198, 120], varname="f_vf_glow")
bp("split", "f_vf_split.maxpat", 1, 2, [595, 984, 117, 80], varname="f_vf_split")

for m in ("advect", "warp", "glow"):
    wire("wfg", 0, m, 0)         # dye / source texture
    wire("fluid", 0, m, 1)       # velocity vecfield
wire("fluid", 0, "split", 0)     # look at the field itself

menu("osel", ["Advect", "Warp", "Glow", "Field X", "Raw field"],
     [745, 984, 140, 22], varname="output_select")
obj("osel1", "+ 1", 2, 1, [745, 1012, 40, 22], ["int"])
obj("oswitch", "switch 5", 6, 1, [745, 1040, 80, 22], ["jit_gl_texture"])
wire("osel", 0, "osel1", 0)
wire("osel1", 0, "oswitch", 0)
for i, m in enumerate(("advect", "warp", "glow", "split", "fluid")):
    wire(m, 0, "oswitch", i + 1)

bp("out", "vs_output.maxpat", 1, 0, [745, 1075, 157, 22], varname="vs_output")
wire("oswitch", 0, "out", 0)


# --------------------------------------------------------------- verify
def verify():
    """Same discipline as build_fluid.py: fail loudly rather than write junk."""
    ids = [b["box"]["id"] for b in boxes]
    dupes = {i for i in ids if ids.count(i) > 1}
    assert not dupes, "duplicate box ids: %s" % sorted(dupes)

    idx = {b["box"]["id"]: b["box"] for b in boxes}
    for ln in lines:
        (s, so), (d, di) = ln["patchline"]["source"], ln["patchline"]["destination"]
        assert s in idx, "wire from unknown box %s" % s
        assert d in idx, "wire to unknown box %s" % d
        assert so < idx[s]["numoutlets"], \
            "%s has no outlet %d (has %d)" % (s, so, idx[s]["numoutlets"])
        assert di < idx[d]["numinlets"], \
            "%s has no inlet %d (has %d)" % (d, di, idx[d]["numinlets"])

    # every force producer and consumer actually reaches a switch
    for m in ("vortex", "flow", "repulse", "optflow"):
        assert any(l["patchline"]["source"][0] == m
                   and l["patchline"]["destination"][0] == "fswitch"
                   for l in lines), "%s not wired to the force switch" % m
    for m in ("advect", "warp", "glow", "split", "fluid"):
        assert any(l["patchline"]["source"][0] == m
                   and l["patchline"]["destination"][0] == "oswitch"
                   for l in lines), "%s not wired to the output switch" % m


PATCHER = {"patcher": {
    "fileversion": 1,
    "appversion": {"major": 9, "minor": 1, "revision": 4,
                   "architecture": "x64", "modernui": 1},
    "classnamespace": "box",
    "rect": [59.0, 114.0, 1180.0, 900.0],
    "boxes": boxes,
    "lines": lines,
}}

if __name__ == "__main__":
    verify()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT, "w") as f:
        json.dump(PATCHER, f, indent=2)
    json.load(open(OUT))  # JSON validate after every .maxpat write
    print("wrote %s (%d boxes, %d lines) -- VALID"
          % (OUT, len(boxes), len(lines)))
