"""
make_module_bench.py -- generate tests/bench/bench_module.maxpat, the E3
module bench (.specify/test_bench/tasks_extensions.md T102), plus the empty
placeholder patcher its slot starts with.

Separate from bench.maxpat because it embeds Vsynth's real `vs_render`
bpatcher, which creates the global `vsynth` context (plus the `draw`/`dim`/
`time` sends and the `vs_black` texture vs_inState relies on). Close Vsynth
performance patches while this bench is open.

Modules are never cabled to the bench: bench_module.js loads a generated
per-job wrapper patch into the cordless slot `bench_mslot` with
`script sendbox bench_mslot replace <wrapper>`. The wrapper contains the
module as a bpatcher wired to [r bench_minK] (inputs / control messages) and
[s bench_moutK] (outputs), so varying module inlet/outlet counts can't delete
anything here.

Ports: 7473 in, 7474 out (the codebox bench uses 7471/7472).
Run:  python3 tests/bench/make_module_bench.py
"""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE / "bench_module.maxpat"
EMPTY = HERE / "bench_module_empty.maxpat"
N_IN = 5          # module inlets supported (main + up to 4 mod inlets)
N_OUT = 4         # module outlets captured

boxes, lines = [], []


def obj(oid, text, n_in, n_out, rect, outlettype=None, varname=None):
    box = {"id": oid, "maxclass": "newobj", "text": text, "numinlets": n_in,
           "numoutlets": n_out, "patching_rect": [float(v) for v in rect]}
    if n_out:
        box["outlettype"] = outlettype or [""] * n_out
    if varname:
        box["varname"] = varname
    boxes.append({"box": box})


def wire(s, so, d, di):
    lines.append({"patchline": {"source": [s, so], "destination": [d, di]}})


def patcher(bxs, lns, rect=(100.0, 100.0, 900.0, 640.0)):
    return {"patcher": {"fileversion": 1,
                        "appversion": {"major": 9, "minor": 1, "revision": 4,
                                       "architecture": "x64", "modernui": 1},
                        "classnamespace": "box", "rect": list(rect),
                        "boxes": bxs, "lines": lns}}


boxes.append({"box": {"id": "c-title", "maxclass": "comment", "numinlets": 1, "numoutlets": 0,
                      "text": "f_ MODULE bench -- generated by make_module_bench.py, do not edit. "
                              "Logic: bench_module.js. Close Vsynth patches while open.",
                      "patching_rect": [20.0, 10.0, 700.0, 20.0]}})

obj("udprecv", "udpreceive 7473", 1, 1, [20, 50, 110, 22])
obj("err", "error 1", 1, 1, [150, 50, 60, 22])
obj("errdefer", "deferlow", 1, 1, [150, 75, 60, 22])
obj("errprep", "prepend bench_error", 1, 1, [150, 100, 120, 22])
obj("rdraw", "r draw", 0, 1, [300, 50, 50, 22])
obj("js", "js bench_module.js", 3, 1, [20, 140, 330, 22], varname="bench_module_js")
obj("udpsend", "udpsend 127.0.0.1 7474", 1, 0, [20, 180, 160, 22])
wire("udprecv", 0, "js", 0)
wire("err", 0, "errdefer", 0)
wire("errdefer", 0, "errprep", 0)
wire("errprep", 0, "js", 1)
wire("rdraw", 0, "js", 2)
wire("js", 0, "udpsend", 0)

# Vsynth's real renderer: vsynth context, qmetro -> [s draw], dim, vs_black.
# Controlled through a cord from [r bench_vsctl]: a js message() to a
# bpatcher goes to its patcher object, not into its inlet (2026-09-22:
# "jpatcher: doesn't understand enable").
boxes.append({"box": {"id": "vsrender", "maxclass": "bpatcher", "name": "vs_render.maxpat",
                      "numinlets": 1, "numoutlets": 0, "varname": "bench_vsrender",
                      "patching_rect": [420.0, 80.0, 220.0, 120.0]}})
obj("vsctl", "r bench_vsctl", 0, 1, [420, 50, 100, 22])
wire("vsctl", 0, "vsrender", 0)

for k in range(1, N_IN + 1):
    x = 20 + (k - 1) * 175
    obj(f"mat{k}", f"jit.matrix bench_mmat{k} 4 float32 64 64", 1, 2, [x, 230, 165, 22],
        ["jit_matrix", ""], varname=f"bench_mmat{k}")
    obj(f"tex{k}", f"jit.gl.texture vsynth @name bench_mtex{k} @type float32", 1, 2,
        [x, 260, 165, 22], ["jit_gl_texture", ""], varname=f"bench_mtex{k}")
    wire(f"mat{k}", 0, f"tex{k}", 0)

# cordless slot for the per-job wrapper
boxes.append({"box": {"id": "slot", "maxclass": "bpatcher", "name": "bench_module_empty.maxpat",
                      "numinlets": 0, "numoutlets": 0, "varname": "bench_mslot",
                      "patching_rect": [20.0, 310.0, 200.0, 60.0]}})

for k in range(1, N_OUT + 1):
    x = 250 + (k - 1) * 160
    obj(f"rout{k}", f"r bench_mout{k}", 0, 1, [x, 310, 100, 22])
    obj(f"gate{k}", "gate", 2, 1, [x, 340, 40, 22], varname=f"bench_mgate{k}")
    obj(f"cap{k}", f"jit.matrix bench_mcap{k} 4 float32 1 1 @adapt 1", 1, 2, [x, 370, 150, 22],
        ["jit_matrix", ""], varname=f"bench_mcap{k}")
    wire(f"rout{k}", 0, f"gate{k}", 1)
    wire(f"gate{k}", 0, f"cap{k}", 0)

if __name__ == "__main__":
    with open(OUT, "w") as f:
        json.dump(patcher(boxes, lines), f, indent=2)
    empty = [{"box": {"id": "c", "maxclass": "comment", "numinlets": 1, "numoutlets": 0,
                      "text": "(empty module slot)", "patching_rect": [5.0, 5.0, 150.0, 20.0]}}]
    with open(EMPTY, "w") as f:
        json.dump(patcher(empty, [], rect=(100.0, 100.0, 200.0, 60.0)), f, indent=2)
    print(f"wrote {OUT.name} ({len(boxes)} boxes, {len(lines)} lines) and {EMPTY.name}")
