"""
make_bench.py -- generate tests/bench/bench.maxpat (plan.md ADR-2).

The bench is objects and wiring only; all logic is in bench.js. Regenerating
is always safe (no hand-built UI). Every object bench.js addresses has a
scripting name (varname).

Layout of the signal path:
    [udpreceive 7471] -> [js bench.js] -> [udpsend 127.0.0.1 7472]
    [error 1] -> js inlet 1
    [jit.world bench_ctx] draw bang -> [t b b]: right -> js inlet 2 (frame
        counted FIRST), left -> bang [jit.gl.texture bench_tex1]
    [jit.matrix bench_inK] -> [jit.gl.texture bench_texK]   (K = 1..3)
    bench_tex1 -> bench_src -> bench_p1 -> ... -> bench_p8   (inlet 0 chain)
    bench_p1 -> [gate] (right inlet) -> [jit.matrix bench_out]

Constant 3 inlets per slot: jit.gl.pix's `inputs` is read-only and follows
the gen patcher's `in` objects. So the slots start from bench_default.genjit
(written here: in 1..3, out1 = in1) and every job's .genjit also carries
in 1..3 (genjit.make_genjit(min_inputs=3)). Inlet counts never change, so
bench_tex2 / bench_tex3 are plain physical cords into inlets 1 / 2 of every
slot. (2026-09-22: delivering them by message from bench.js failed --
`activeinput` + jit_gl_texture landed on input 0; `sendinput N
jit_gl_texture` did not set the input.)

Run:  tests/run.sh tests/bench/make_bench.py   (or plain python3; stdlib only)
"""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent / "bench.maxpat"
N_SLOTS = 8
N_INPUTS = 3

boxes, lines = [], []


def obj(oid, text, n_in, n_out, rect, outlettype=None, varname=None, maxclass="newobj"):
    box = {"id": oid, "maxclass": maxclass, "text": text,
           "numinlets": n_in, "numoutlets": n_out,
           "patching_rect": [float(v) for v in rect]}
    if n_out:
        box["outlettype"] = outlettype or [""] * n_out
    if varname:
        box["varname"] = varname
    boxes.append({"box": box})
    return oid


def comment(oid, text, rect):
    boxes.append({"box": {"id": oid, "maxclass": "comment", "text": text,
                          "numinlets": 1, "numoutlets": 0,
                          "patching_rect": [float(v) for v in rect]}})


def wire(src, so, dst, di):
    lines.append({"patchline": {"source": [src, so], "destination": [dst, di]}})


comment("c-title", "f_ test bench -- generated by make_bench.py, do not edit. "
        "Logic: bench.js. Spec: .specify/test_bench/", [20, 10, 620, 20])

obj("udprecv", "udpreceive 7471", 1, 1, [20, 50, 110, 22])
# [error] -> [deferlow] -> [prepend bench_error] -> js inlet 1.
# 2026-09-22: wiring [error] straight into js caused an error feedback loop
# (js re-reported the incoming error, [error] caught that, recursion ->
# Max stack overflow -> all outlets disabled). deferlow makes any loop
# asynchronous instead of stack-recursive; the prepend gives js a harmless
# selector instead of `error`.
obj("err", "error 1", 1, 1, [150, 50, 60, 22])
obj("errdefer", "deferlow", 1, 1, [150, 75, 60, 22])
obj("errprep", "prepend bench_error", 1, 1, [150, 100, 120, 22])
obj("world", "jit.world bench_ctx @enable 1 @size 256 256", 1, 3, [240, 50, 290, 22],
    ["jit_gl_texture", "bang", ""], varname="bench_world")
obj("tbb", "t b b", 1, 2, [240, 85, 50, 22], ["bang", "bang"])
obj("js", "js bench.js", 3, 1, [20, 130, 290, 22], varname="bench_js")
obj("udpsend", "udpsend 127.0.0.1 7472", 1, 0, [20, 170, 160, 22])

wire("udprecv", 0, "js", 0)
wire("err", 0, "errdefer", 0)
wire("errdefer", 0, "errprep", 0)
wire("errprep", 0, "js", 1)
wire("world", 1, "tbb", 0)
wire("tbb", 1, "js", 2)
wire("js", 0, "udpsend", 0)

for k in range(1, N_INPUTS + 1):
    x = 20 + (k - 1) * 250
    obj(f"mat{k}", f"jit.matrix bench_in{k} 4 float32 64 64", 1, 2, [x, 230, 230, 22],
        ["jit_matrix", ""], varname=f"bench_in{k}")
    obj(f"tex{k}", f"jit.gl.texture bench_ctx @name bench_tex{k} @type float32",
        1, 2, [x, 265, 230, 22], ["jit_gl_texture", ""], varname=f"bench_tex{k}")
    wire(f"mat{k}", 0, f"tex{k}", 0)
wire("tbb", 0, "tex1", 0)

# bench_src: identity pass between bench_tex1 and slot 1, so slot 1 is fed
# a texture every frame by an upstream pix exactly like slots 2..K are.
# Verified 2026-09-22 that slot 1 recomputes every frame with bench_src in
# place (heavy codebox: K=1 8.8 ms/frame, K=2 17.3 ms). NOT established
# whether it would without bench_src -- an earlier "cached re-emit" reading
# of the perf numbers turned out to be CPU/GPU overlap (plan ADR-9 rev. 2).
obj("src", "jit.gl.pix bench_ctx @gen bench_default @adapt 1 @type float32", 3, 2,
    [20, 295, 400, 22], ["jit_gl_texture", ""], varname="bench_src")
wire("tex1", 0, "src", 0)
prev = "src"
for k in range(1, N_SLOTS + 1):
    bypass = "" if k == 1 else " @bypass 1"
    obj(f"p{k}", f"jit.gl.pix bench_ctx @gen bench_default @adapt 0 @dim 256 256 "
        f"@type float32{bypass}",
        3, 2, [20, 330 + (k - 1) * 35, 400, 22], ["jit_gl_texture", ""],
        varname=f"bench_p{k}")
    wire(prev, 0, f"p{k}", 0)
    wire("tex2", 0, f"p{k}", 1)
    wire("tex3", 0, f"p{k}", 2)
    prev = f"p{k}"

obj("gate", "gate", 2, 1, [450, 320, 40, 22], varname="bench_gate")
obj("outmat", "jit.matrix bench_out 4 float32 256 256 @adapt 1", 1, 2,
    [450, 360, 290, 22], ["jit_matrix", ""], varname="bench_out")
wire("p1", 0, "gate", 1)
wire("gate", 0, "outmat", 0)

patcher = {"patcher": {
    "fileversion": 1,
    "appversion": {"major": 9, "minor": 1, "revision": 4,
                   "architecture": "x64", "modernui": 1},
    "classnamespace": "box",
    "rect": [100.0, 100.0, 780.0, 660.0],
    "boxes": boxes,
    "lines": lines,
}}

if __name__ == "__main__":
    import sys
    sys.path.insert(0, str(OUT.parent.parent))          # tests/
    from genjit import write_genjit
    write_genjit(OUT.parent / "bench_default.genjit", "out1 = in1;", min_inputs=3)
    with open(OUT, "w") as f:
        json.dump(patcher, f, indent=2)
    print(f"wrote {OUT} ({len(boxes)} boxes, {len(lines)} lines)")
